(in-package #:clabber)

;;; Emoji shortcode expansion
;;; Converts :shortcode: patterns to Unicode emoji characters

(defvar *emoji-table* (make-hash-table :test 'equal))

(defun init-emoji-table ()
  "Initialize the emoji shortcode lookup table."
  (clrhash *emoji-table*)
  (loop for (code . emoji) in
        '(;; Smileys & People
          ("smile" . "😄") ("laughing" . "😆") ("blush" . "😊")
          ("smiley" . "😃") ("grinning" . "😀") ("grin" . "😁")
          ("joy" . "😂") ("rofl" . "🤣") ("relaxed" . "☺️")
          ("wink" . "😉") ("kiss" . "💋") ("kissing" . "�😗") ("kissing_heart" . "😘")
          ("kissing_closed_eyes" . "😚") ("kissing_smiling_eyes" . "😙")
          ("heart_eyes" . "😍")
          ("yum" . "😋") ("stuck_out_tongue" . "😛")
          ("stuck_out_tongue_winking_eye" . "😜")
          ("stuck_out_tongue_closed_eyes" . "😝")
          ("sunglasses" . "😎") ("smirk" . "😏")
          ("unamused" . "😒") ("disappointed" . "😞") ("pensive" . "😔")
          ("worried" . "😟") ("confused" . "😕") ("slightly_frowning_face" . "🙁")
          ("frowning" . "😦") ("persevere" . "😣") ("confounded" . "😖")
          ("tired_face" . "😫") ("weary" . "😩") ("cry" . "😢")
          ("sob" . "😭") ("triumph" . "😤") ("angry" . "😠")
          ("rage" . "😡") ("no_mouth" . "😶") ("neutral_face" . "😐")
          ("expressionless" . "😑") ("hushed" . "😯") ("flushed" . "😳")
          ("astonished" . "😲") ("open_mouth" . "😮") ("scream" . "😱")
          ("fearful" . "😨") ("cold_sweat" . "😰") ("sweat" . "😓")
          ("sleeping" . "😴") ("dizzy_face" . "😵") ("thinking" . "🤔")
          ("lying_face" . "🤥") ("zipper_mouth" . "🤐")
          ("nerd" . "🤓") ("cowboy" . "🤠") ("clown" . "🤡")
          ("mask" . "😷") ("thermometer_face" . "🤒")
          ("skull" . "💀") ("ghost" . "👻") ("alien" . "👽")
          ("robot" . "🤖") ("poop" . "💩") ("hankey" . "💩")
          ("imp" . "😈") ("devil" . "👿") ("japanese_ogre" . "👹")
          ;; Gestures
          ("thumbsup" . "👍") ("+1" . "👍") ("thumbsdown" . "👎")
          ("-1" . "👎") ("ok_hand" . "👌") ("punch" . "👊")
          ("fist" . "✊") ("wave" . "👋") ("clap" . "👏")
          ("raised_hands" . "🙌") ("pray" . "🙏") ("handshake" . "🤝")
          ("point_up" . "☝️") ("point_down" . "👇")
          ("point_left" . "👈") ("point_right" . "👉")
          ("middle_finger" . "🖕") ("muscle" . "💪")
          ;; Hearts & Symbols
          ("heart" . "❤️") ("orange_heart" . "🧡") ("yellow_heart" . "💛")
          ("green_heart" . "💚") ("blue_heart" . "💙") ("purple_heart" . "💜")
          ("black_heart" . "🖤") ("broken_heart" . "💔")
          ("sparkling_heart" . "💖") ("heartpulse" . "💗")
          ("heartbeat" . "💓") ("two_hearts" . "💕")
          ("revolving_hearts" . "💞") ("cupid" . "💘")
          ("gift_heart" . "💝") ("heart_exclamation" . "❣️")
          ("100" . "💯") ("fire" . "🔥") ("star" . "⭐")
          ("star2" . "🌟") ("sparkles" . "✨") ("zap" . "⚡")
          ("boom" . "💥") ("collision" . "💥") ("sweat_drops" . "💦")
          ("dash" . "💨") ("hole" . "🕳️") ("bomb" . "💣")
          ("speech_balloon" . "💬") ("thought_balloon" . "💭")
          ("zzz" . "💤") ("wave_dash" . "〰️")
          ;; Animals
          ("dog" . "🐶") ("cat" . "🐱") ("mouse" . "🐭")
          ("hamster" . "🐹") ("rabbit" . "🐰") ("fox" . "🦊")
          ("bear" . "🐻") ("panda" . "🐼") ("koala" . "🐨")
          ("tiger" . "🐯") ("lion" . "🦁") ("cow" . "🐮")
          ("pig" . "🐷") ("frog" . "🐸") ("monkey" . "🐵")
          ("chicken" . "🐔") ("penguin" . "🐧") ("bird" . "🐦")
          ("eagle" . "🦅") ("owl" . "🦉") ("bat" . "🦇")
          ("wolf" . "🐺") ("horse" . "🐴") ("unicorn" . "🦄")
          ("bee" . "🐝") ("bug" . "🐛") ("butterfly" . "🦋")
          ("snail" . "🐌") ("octopus" . "🐙") ("turtle" . "🐢")
          ("snake" . "🐍") ("shark" . "🦈") ("whale" . "🐳")
          ("dolphin" . "🐬") ("fish" . "🐟") ("crab" . "🦀")
          ("shrimp" . "🦐") ("squid" . "🦑") ("dragon" . "🐉")
          ;; Food & Drink
          ("apple" . "🍎") ("green_apple" . "🍏") ("pear" . "🍐")
          ("orange" . "🍊") ("lemon" . "🍋") ("banana" . "🍌")
          ("watermelon" . "🍉") ("grapes" . "🍇") ("strawberry" . "🍓")
          ("peach" . "🍑") ("cherries" . "🍒") ("pizza" . "🍕")
          ("hamburger" . "🍔") ("fries" . "🍟") ("hotdog" . "🌭")
          ("taco" . "🌮") ("burrito" . "🌯") ("egg" . "🥚")
          ("coffee" . "☕") ("tea" . "🍵") ("beer" . "🍺")
          ("beers" . "🍻") ("wine_glass" . "🍷") ("cocktail" . "🍸")
          ("tropical_drink" . "🍹") ("champagne" . "🍾")
          ("cake" . "🎂") ("cookie" . "🍪") ("chocolate_bar" . "🍫")
          ("candy" . "🍬") ("lollipop" . "🍭") ("ice_cream" . "🍨")
          ("doughnut" . "🍩") ("popcorn" . "🍿")
          ;; Activities & Objects
          ("soccer" . "⚽") ("basketball" . "🏀") ("football" . "🏈")
          ("baseball" . "⚾") ("tennis" . "🎾") ("trophy" . "🏆")
          ("medal" . "🏅") ("guitar" . "🎸") ("microphone" . "🎤")
          ("headphones" . "🎧") ("video_game" . "🎮") ("joystick" . "🕹️")
          ("dart" . "🎯") ("dice" . "🎲") ("musical_note" . "🎵")
          ("notes" . "🎶") ("art" . "🎨") ("movie_camera" . "🎥")
          ("camera" . "📷") ("tv" . "📺") ("computer" . "💻")
          ("keyboard" . "⌨️") ("phone" . "📱") ("email" . "📧")
          ("mailbox" . "📫") ("package" . "📦") ("pencil" . "✏️")
          ("memo" . "📝") ("book" . "📖") ("books" . "📚")
          ("link" . "🔗") ("paperclip" . "📎") ("scissors" . "✂️")
          ("lock" . "🔒") ("unlock" . "🔓") ("key" . "🔑")
          ("hammer" . "🔨") ("wrench" . "🔧") ("gear" . "⚙️")
          ("bulb" . "💡") ("flashlight" . "🔦") ("mag" . "🔍")
          ;; Nature & Weather
          ("sunny" . "☀️") ("cloud" . "☁️") ("umbrella" . "☂️")
          ("snowflake" . "❄️") ("rainbow" . "🌈") ("ocean" . "🌊")
          ("earth" . "🌍") ("volcano" . "🌋") ("milky_way" . "🌌")
          ("crescent_moon" . "🌙") ("full_moon" . "🌕")
          ("sun_with_face" . "🌞") ("moon_face" . "🌝")
          ("fallen_leaf" . "🍂") ("maple_leaf" . "🍁")
          ("four_leaf_clover" . "🍀") ("herb" . "🌿")
          ("cactus" . "🌵") ("palm_tree" . "🌴") ("evergreen_tree" . "🌲")
          ("rose" . "🌹") ("sunflower" . "🌻") ("tulip" . "🌷")
          ("cherry_blossom" . "🌸") ("bouquet" . "💐")
          ("mushroom" . "🍄") ("chestnut" . "🌰")
          ;; Flags & Misc
          ("checkered_flag" . "🏁") ("triangular_flag" . "🚩")
          ("white_flag" . "🏳️") ("rainbow_flag" . "🏳️‍🌈")
          ("pirate_flag" . "🏴‍☠️")
          ("warning" . "⚠️") ("no_entry" . "⛔")
          ("x" . "❌") ("o" . "⭕") ("bangbang" . "‼️")
          ("question" . "❓") ("exclamation" . "❗")
          ("white_check_mark" . "✅") ("heavy_check_mark" . "✔️")
          ("ballot_box_with_check" . "☑️")
          ("recycle" . "♻️") ("copyright" . "©️") ("registered" . "®️")
          ("tm" . "™️") ("infinity" . "♾️")
          ;; Faces extras
          ("eyes" . "👀") ("eye" . "👁️") ("tongue" . "👅")
          ("lips" . "👄") ("brain" . "🧠") ("bone" . "🦴")
          ;; Tech / Dev
          ("rocket" . "🚀") ("satellite" . "🛰️") ("flying_saucer" . "🛸")
          ("shield" . "🛡️") ("crossed_swords" . "⚔️")
          ("skull_crossbones" . "☠️") ("radioactive" . "☢️")
          ("biohazard" . "☣️") ("atom" . "⚛️")
          ;; Common chat
          ("thumbs_up" . "👍") ("thumbs_down" . "👎")
          ("ok" . "👌") ("v" . "✌️") ("peace" . "✌️")
          ("shrug" . "🤷") ("facepalm" . "🤦")
          ("party" . "🎉") ("tada" . "🎉") ("confetti" . "🎊")
          ("balloon" . "🎈") ("gift" . "🎁") ("ribbon" . "🎀")
          ("crown" . "👑") ("gem" . "💎") ("ring" . "💍")
          ("money" . "💰") ("dollar" . "💵") ("moneybag" . "💰")
          ("chart" . "📈") ("chart_down" . "📉")
          ("bell" . "🔔") ("no_bell" . "🔕")
          ("mega" . "📣") ("loudspeaker" . "📢")
          ("pin" . "📌") ("pushpin" . "📍")
          ("flag" . "🚩") ("checkmark" . "✅")
          ("cross" . "❌") ("stop" . "🛑")
          ("sos" . "🆘") ("new" . "🆕") ("free" . "🆓")
          ("up" . "🆙") ("cool" . "🆒") ("ng" . "🆖")
          ;; Lisp / Hacker
          ("lambda" . "λ") ("lisp" . "λ") ("parens" . "()")
          ("hacker" . "👨‍💻") ("woman_technologist" . "👩‍💻"))
        do (setf (gethash code *emoji-table*) emoji)))

(defun emoji-expand (text)
  "Replace :shortcode: patterns in TEXT with their emoji equivalents."
  (let ((result (make-array (length text) :element-type 'character
                            :adjustable t :fill-pointer 0))
        (i 0)
        (len (length text)))
    (loop while (< i len)
          do (if (char= (char text i) #\:)
                 ;; Look for closing :
                 (let ((end (position #\: text :start (1+ i))))
                   (if (and end (> end (1+ i))
                            ;; No spaces inside shortcode
                            (not (position #\Space text :start (1+ i) :end end)))
                       (let* ((code (subseq text (1+ i) end))
                              (emoji (gethash code *emoji-table*)))
                         (if emoji
                             (progn
                               (loop for c across emoji
                                     do (vector-push-extend c result))
                               (setf i (1+ end)))
                             ;; Not a known shortcode, keep the :
                             (progn
                               (vector-push-extend #\: result)
                               (incf i))))
                       ;; No closing : or empty, keep the :
                       (progn
                         (vector-push-extend #\: result)
                         (incf i))))
                 (progn
                   (vector-push-extend (char text i) result)
                   (incf i))))
    (coerce result 'string)))

(defun emoji-complete (prefix)
  "Return list of (code . emoji) pairs matching PREFIX, sorted by code."
  (let ((matches nil))
    (maphash (lambda (code emoji)
               (when (and (>= (length code) (length prefix))
                          (string= prefix code :end2 (length prefix)))
                 (push (cons code emoji) matches)))
             *emoji-table*)
    (sort matches #'string< :key #'car)))

;; Initialize on load
(init-emoji-table)
