(in-package #:clabber)

(defparameter *version* "2.0.0-alpha")

(defun print-help ()
  (format t "CLabber - XMPP Chat Client~%~%")
  (format t "Usage: clabber [options]~%~%")
  (format t "Options:~%")
  (format t "  -h, help       Show this help message~%")
  (format t "  -v, version    Show version information~%")
  (format t "~%")
  (format t "Commands:~%")
  (format t "  /join room@server   Join a MUC room~%")
  (format t "  /msg jid            Open DM with contact~%")
  (format t "  /quit               Disconnect and exit~%")
  (format t "  /help               Show all commands~%")
  (format t "~%")
  (format t "Navigation:~%")
  (format t "  Ctrl-P/N         Previous/Next buffer~%")
  (format t "  Ctrl-W           Cycle split-pane mode~%")
  (format t "  PgUp/PgDn        Scroll chat history~%")
  (format t "  Ctrl-Q           Quit~%")
  (format t "~%Configuration: ~~/.config/clabber/config.lisp~%"))

(defun print-version ()
  (format t "CLabber ~a~%" *version*))

(defun main ()
  (let ((args (uiop:command-line-arguments)))
    (cond
      ((member "-h" args :test #'string=)
       (print-help))
      ((member "-v" args :test #'string=)
       (print-version))
      ((member "help" args :test #'string=)
       (print-help))
      ((member "version" args :test #'string=)
       (print-version))
      (t
       (let* ((cfg (load-config))
              (app (make-app)))
         (setf (app-config app) cfg)
         ;; Resolve passwords BEFORE entering raw terminal mode
         ;; (GPG pinentry needs a normal terminal)
         (app-resolve-passwords app)
         (app-run app)
         (sb-ext:exit))))))
